In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### File Reading

In [2]:
df=pd.read_csv("gplay.csv")

In [3]:
df

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone
...,...,...,...,...,...,...,...,...,...,...
10836,10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone
10837,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone
10838,10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone
10839,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+
10840,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone

In [4]:
df.head()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone

In [5]:
df.tail()

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
10836,10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone
10837,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone
10838,10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone
10839,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+
10840,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10841 non-null  int64
 1   App             10841 non-null  object
 2   Category        10841 non-null  object
 3   Rating          9367 non-null   float64
 4   Reviews         10841 non-null  object
 5   Size            10841 non-null  object
 6   Installs        10841 non-null  object
 7   Type            10840 non-null  object
 8   Price           10841 non-null  object
 9   Content Rating  10840 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 847.1+ KB

In [7]:
df.columns

Index(['Unnamed: 0', 'App', 'Category', 'Rating', 'Reviews', 'Size',
       'Installs', 'Type', 'Price', 'Content Rating'],
      dtype='object')

### TO DROP Unnamed: 0 COLUMN

In [8]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
dtypes: float64(1), object(8)
memory usage: 762.4+ KB

### Find Null Values using --> isnull

In [10]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
dtype: int64

### Filling Null Values Using --> Fillna() By Mean() Value

In [11]:
df['Rating'].fillna(df['Rating'].mean(),inplace=True)

In [12]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
dtype: int64

### Droping values from column -- Type / Content Rating -- using Dropna()

In [13]:
df.dropna(inplace=True)

In [14]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

### Use Value_Counts to see unique values from Columns

In [15]:
df['Reviews'].value_counts()

Reviews
0         595
1         272
2         214
3         175
4         137
         ...
4272        1
5517        1
4057        1
459797      1
398307      1
Name: count, Length: 6001, dtype: int64

In [16]:
df['Category'].value_counts()

Category
FAMILY                 1971
GAME                   1144
TOOLS                   843
MEDICAL                 463
BUSINESS                460
PRODUCTIVITY            424
PERSONALIZATION         392
COMMUNICATION           387
SPORTS                  384
LIFESTYLE               382
FINANCE                 366
HEALTH_AND_FITNESS      341
PHOTOGRAPHY             335
SOCIAL                  295
NEWS_AND_MAGAZINES      283
SHOPPING                260
TRAVEL_AND_LOCAL        258
DATING                  234
BOOKS_AND_REFERENCE     231
VIDEO_PLAYERS           175
EDUCATION               156
ENTERTAINMENT           149
MAPS_AND_NAVIGATION     137
FOOD_AND_DRINK          127
HOUSE_AND_HOME           88
AUTO_AND_VEHICLES        85
LIBRARIES_AND_DEMO       85
WEATHER                  82
ART_AND_DESIGN           65
EVENTS                   64
PARENTING                60
COMICS                   60
BEAUTY                   53
Name: count, dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  object
 4   Size            10839 non-null  object
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(1), object(8)
memory usage: 846.8+ KB

### Changing DataType of coln

In [18]:
df['Reviews']=df['Reviews'].astype(float)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            10839 non-null  object
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(2), object(7)
memory usage: 846.8+ KB

In [20]:
df['Size'].value_counts()

Size
Varies with device    1694
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
430k                     1
429k                     1
200k                     1
460k                     1
619k                     1
Name: count, Length: 461, dtype: int64

In [21]:
def convert_size(x):
    if 'k' in x:
        x=x.replace('k','')
        return float(x)/1024
    elif 'M' in x:
        x=x.replace('M','')
        return float(x)
    elif x=='Varies with device':
        return np.nan
    else:
        return float(x)

In [22]:
df['Size']=df['Size'].map(convert_size)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(3), object(6)
memory usage: 846.8+ KB

### Working on Price coln -- DataType / removing $ from Price

In [24]:
df['Price']=df['Price'].str.replace("$"," ")

In [25]:
df['Price'].value_counts() # To see if $ is replaced to Empty

Price
0         10039
 0.99       148
 2.99       129
 1.99        73
 4.99        72
          ...
 19.90        1
 1.75         1
 14.00        1
 4.85         1
 1.04         1
Name: count, Length: 92, dtype: int64

In [26]:
df['Price']=df['Price'].astype(float) #To change the datatype

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  float64
 8   Content Rating  10839 non-null  object
dtypes: float64(4), object(5)
memory usage: 846.8+ KB

In [28]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,"10,000+",Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,"500,000+",Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,"5,000,000+",Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,"50,000,000+",Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,"100,000+",Free,0.0,Everyone

### Replacing values and DataTpe in 'Installs' col

In [29]:
df['Installs']=df['Installs'].str.replace(',','')
df['Installs']=df['Installs'].str.replace('+','')
df['Installs']=df['Installs'].astype(float)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  float64
 6   Type            10839 non-null  object
 7   Price           10839 non-null  float64
 8   Content Rating  10839 non-null  object
dtypes: float64(5), object(4)
memory usage: 846.8+ KB

In [31]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000.0,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000.0,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000.0,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000.0,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000.0,Free,0.0,Everyone

### Ques

### find highest rating¶

In [32]:
df['Rating'].max()

5.0

### find app with rating 4

In [33]:
df.loc[df['Rating']==4]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450.0,14.000000,100000.0,Free,0.0,Everyone
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591.0,9.400000,500000.0,Free,0.0,Everyone
50,Real Tractor Farming,AUTO_AND_VEHICLES,4.0,1598.0,56.000000,1000000.0,Free,0.0,Everyone
58,Restart Navigator,AUTO_AND_VEHICLES,4.0,1403.0,0.196289,100000.0,Free,0.0,Everyone
66,Used Cars Mexico,AUTO_AND_VEHICLES,4.0,190.0,2.500000,50000.0,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10802,FR: My Famous Lover,FAMILY,4.0,185.0,28.000000,10000.0,Free,0.0,Teen
10814,FR: My Secret Pets!,FAMILY,4.0,785.0,31.000000,50000.0,Free,0.0,Teen
10817,HTC Sense Input - FR,TOOLS,4.0,885.0,8.000000,100000.0,Free,0.0,Everyone
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486.0,NaN,5000000.0,Free,0.0,Mature 17+
10834,FR Calculator,FAMILY,4.0,7.0,2.600000,500.0,Free,0.0,Everyone

In [34]:
df.loc[df['Rating']== df['Rating'].max()]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15.0,37.0,1000.0,Free,0.0,Everyone
612,American Girls Mobile Numbers,DATING,5.0,5.0,4.4,1000.0,Free,0.0,Mature 17+
615,Awake Dating,DATING,5.0,2.0,70.0,100.0,Free,0.0,Mature 17+
633,Spine- The dating app,DATING,5.0,5.0,9.3,500.0,Free,0.0,Teen
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6.0,5.0,100.0,Free,0.0,Mature 17+
...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14.0,16.0,100.0,Free,0.0,Everyone
10742,GKPB FP Online Church,LIFESTYLE,5.0,32.0,7.9,1000.0,Free,0.0,Everyone
10776,Monster Ride Pro,GAME,5.0,1.0,24.0,10.0,Free,0.0,Everyone
10820,Fr. Daoud Lamei,FAMILY,5.0,22.0,8.6,1000.0,Free,0.0,Teen
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6,100.0,Free,0.0,Everyone

### Diplay app name , category and rating whose rating is 5¶

In [35]:
df[['App','Category','Rating']].loc[df['Rating']==5]

                                              App   Category  Rating
329                  Hojiboy Tojiboyev Life Hacks     COMICS     5.0
612                 American Girls Mobile Numbers     DATING     5.0
615                                  Awake Dating     DATING     5.0
633                         Spine- The dating app     DATING     5.0
636    Girls Live Talk - Free Text and Video Chat     DATING     5.0
...                                           ...        ...     ...
10721                           Mad Dash Fo' Cash       GAME     5.0
10742                       GKPB FP Online Church  LIFESTYLE     5.0
10776                            Monster Ride Pro       GAME     5.0
10820                             Fr. Daoud Lamei     FAMILY     5.0
10837            Fr. Mike Schmitz Audio Teachings     FAMILY     5.0

[274 rows x 3 columns]

In [36]:
df.loc[df['Type']=='Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159.0,19.0,10000.0,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.900000,967.0,14.0,500000.0,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510.0,8.7,5000000.0,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644.0,25.0,50000000.0,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967.0,2.8,100000.0,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38.0,53.0,5000.0,Free,0.0,Everyone
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4.0,3.6,100.0,Free,0.0,Everyone
10838,Parkinson Exercices FR,MEDICAL,4.193338,3.0,9.5,1000.0,Free,0.0,Everyone
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114.0,NaN,1000.0,Free,0.0,Mature 17+
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307.0,19.0,10000000.0,Free,0.0,Everyone

### App Name , Category , and Price for most Expensive App

In [37]:

df[['App','Category','Price']].loc[df['Price'] == df['Price'].max()]

                           App   Category  Price
4367  I'm Rich - Trump Edition  LIFESTYLE  400.0

### Diplay All Records Whose Rating Is Between 4 And 5

In [38]:

df.loc[(df['Rating']>=4)& (df['Rating']<=5)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159.0,19.0,10000.0,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510.0,8.7,5000000.0,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644.0,25.0,50000000.0,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967.0,2.8,100000.0,Free,0.0,Everyone
5,Paper flowers instructions,ART_AND_DESIGN,4.400000,167.0,5.6,50000.0,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38.0,53.0,5000.0,Free,0.0,Everyone
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4.0,3.6,100.0,Free,0.0,Everyone
10838,Parkinson Exercices FR,MEDICAL,4.193338,3.0,9.5,1000.0,Free,0.0,Everyone
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114.0,NaN,1000.0,Free,0.0,Mature 17+
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307.0,19.0,10000000.0,Free,0.0,Everyone

## Display Free Apps With Rating 5

In [45]:
df.loc[(df['Type']=='Free') & (df["Rating"]==5)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15.0,37.0,1000.0,Free,0.0,Everyone
612,American Girls Mobile Numbers,DATING,5.0,5.0,4.4,1000.0,Free,0.0,Mature 17+
615,Awake Dating,DATING,5.0,2.0,70.0,100.0,Free,0.0,Mature 17+
633,Spine- The dating app,DATING,5.0,5.0,9.3,500.0,Free,0.0,Teen
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6.0,5.0,100.0,Free,0.0,Mature 17+
...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14.0,16.0,100.0,Free,0.0,Everyone
10742,GKPB FP Online Church,LIFESTYLE,5.0,32.0,7.9,1000.0,Free,0.0,Everyone
10776,Monster Ride Pro,GAME,5.0,1.0,24.0,10.0,Free,0.0,Everyone
10820,Fr. Daoud Lamei,FAMILY,5.0,22.0,8.6,1000.0,Free,0.0,Teen
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6,100.0,Free,0.0,Everyone

### Display Details Of Lowest Rated App With Free Category

In [46]:
df.loc[(df['Rating']==df['Rating'].min())& (df['Type'] == 'Free')]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
625,House party - live chat,DATING,1.0,1.0,9.2,10.0,Free,0.0,Mature 17+
5151,Clarksburg AH,MEDICAL,1.0,1.0,28.0,50.0,Free,0.0,Everyone
6319,BJ Bridge Standard American 2018,GAME,1.0,1.0,4.9,1000.0,Free,0.0,Everyone
6490,MbH BM,MEDICAL,1.0,1.0,2.3,100.0,Free,0.0,Everyone
7144,CB Mobile Biz,FINANCE,1.0,3.0,8.4,500.0,Free,0.0,Everyone
7383,Thistletown CI,PRODUCTIVITY,1.0,1.0,6.6,100.0,Free,0.0,Everyone
7427,CJ DVD Rentals,COMMUNICATION,1.0,5.0,13.0,100.0,Free,0.0,Everyone
7806,CR Magazine,BUSINESS,1.0,1.0,7.8,100.0,Free,0.0,Everyone
7926,Tech CU Card Manager,FINANCE,1.0,2.0,7.2,1000.0,Free,0.0,Everyone
8820,DS Creator 2.0,TOOLS,1.0,2.0,4.4,500.0,Free,0.0,Everyone
8875,DT future1 cam,TOOLS,1.0,1.0,24.0,50.0,Free,0.0,Everyone
10324,FE Mechanical Engineering Prep,FAMILY,1.0,2.0,21.0,1000.0,Free,0.0,Everyone
10400,Familial Hypercholesterolaemia Handbook,MEDICAL,1.0,2.0,33.0,100.0,Free,0.0,Everyone
10591,Lottery Ticket Checker - Florida Results & Lotto,TOOLS,1.0,3.0,41.0,500.0,Free,0.0,Everyone

### Max Rating & Min Rating

In [47]:
df['Rating'].max()

5.0

In [48]:
df['Rating'].min()

1.0

### Display Rating with 3 & 4

In [49]:
df.loc[(df["Rating"] == 4) | (df["Rating"] == 3)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450.0,14.000000,100000.0,Free,0.0,Everyone
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591.0,9.400000,500000.0,Free,0.0,Everyone
50,Real Tractor Farming,AUTO_AND_VEHICLES,4.0,1598.0,56.000000,1000000.0,Free,0.0,Everyone
58,Restart Navigator,AUTO_AND_VEHICLES,4.0,1403.0,0.196289,100000.0,Free,0.0,Everyone
66,Used Cars Mexico,AUTO_AND_VEHICLES,4.0,190.0,2.500000,50000.0,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10802,FR: My Famous Lover,FAMILY,4.0,185.0,28.000000,10000.0,Free,0.0,Teen
10814,FR: My Secret Pets!,FAMILY,4.0,785.0,31.000000,50000.0,Free,0.0,Teen
10817,HTC Sense Input - FR,TOOLS,4.0,885.0,8.000000,100000.0,Free,0.0,Everyone
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486.0,NaN,5000000.0,Free,0.0,Mature 17+
10834,FR Calculator,FAMILY,4.0,7.0,2.600000,500.0,Free,0.0,Everyone